version: '3.8'

services:
  app:
    build: .
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - .:/app
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
    ports:
      - "4200:4200"
    command: python src/main.py

